version: '3.7'
services:
  web:
    build:
      context: docker/development/nginx
    volumes:
      - ./:/app
    ports:
      - '8080:80'

  php-fpm:
    #container_name: php-fpm
    build:
      context: docker/development/php-fpm
    volumes:
      - ./:/app

  db:
    build:
      context: docker/development/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db_data_container:/var/lib/mysql

  node:
    image: node:8.6-alpine
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true

volumes:
  mysql_db_data_container:
