version: '3.7'
services:
  web:
    build:
      context: docker/development/nginx
    volumes:
      - ./:/app
    ports:
      - '8080:80'

  php-fpm:
    #container_name: php-fpm
    build:
      context: docker/development/php-fpm
    volumes:
      - ./:/app

  db:
    build:
      context: docker/development/mysql
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - mysql_db_data_container:/var/lib/mysql

volumes:
  mysql_db_data_container:
